import {
  Code, Globe, Smartphone, Cloud, Brain, Bot, Zap, Database,
  Server, Layout, ShoppingCart, Search, Gauge, Wrench, Shield,
  Layers, Monitor, Settings, Cpu, PenTool
} from 'lucide-react';

export const SERVICES = [
  {
    slug: 'custom-software-development',
    title: 'Custom Software Development',
    shortDesc: 'Tailor-made software solutions designed to solve your unique business challenges.',
    icon: Code,
    category: 'Development',
    benefits: ['Scalable architecture', 'Custom workflows', 'Seamless integrations', 'Future-proof technology'],
    technologies: ['React', 'Node.js', 'Python', 'PostgreSQL', 'AWS'],
    process: ['Discovery & Analysis', 'Architecture Design', 'Agile Development', 'Testing & QA', 'Deployment & Support'],
  },
  {
    slug: 'website-development',
    title: 'Website Development',
    shortDesc: 'High-performance, SEO-optimized websites that convert visitors into customers.',
    icon: Globe,
    category: 'Development',
    benefits: ['Lightning fast', 'SEO optimized', 'Mobile responsive', 'Conversion focused'],
    technologies: ['Next.js', 'React', 'WordPress', 'Webflow', 'Vercel'],
    process: ['Strategy & Planning', 'UI/UX Design', 'Development', 'Content Integration', 'Launch & Optimize'],
  },
  {
    slug: 'web-applications',
    title: 'Web Applications',
    shortDesc: 'Powerful web apps with real-time features, dashboards, and complex business logic.',
    icon: Monitor,
    category: 'Development',
    benefits: ['Real-time updates', 'Role-based access', 'Data visualization', 'Offline capable'],
    technologies: ['React', 'Vue.js', 'Node.js', 'MongoDB', 'Redis'],
    process: ['Requirements Analysis', 'Prototyping', 'Sprint Development', 'Integration Testing', 'Continuous Deployment'],
  },
  {
    slug: 'mobile-applications',
    title: 'Mobile Applications',
    shortDesc: 'Native and cross-platform mobile apps that deliver exceptional user experiences.',
    icon: Smartphone,
    category: 'Development',
    benefits: ['Cross-platform', 'Offline support', 'Push notifications', 'App Store optimization'],
    technologies: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Firebase'],
    process: ['Market Research', 'UX Design', 'Development', 'Beta Testing', 'App Store Launch'],
  },
  {
    slug: 'saas-development',
    title: 'SaaS Development',
    shortDesc: 'End-to-end SaaS platforms with subscription management, multi-tenancy, and analytics.',
    icon: Layers,
    category: 'Development',
    benefits: ['Multi-tenant architecture', 'Subscription billing', 'Usage analytics', 'API-first design'],
    technologies: ['Next.js', 'Node.js', 'Stripe', 'PostgreSQL', 'AWS'],
    process: ['Market Validation', 'MVP Design', 'Core Development', 'Beta Launch', 'Scale & Iterate'],
  },
  {
    slug: 'ai-development',
    title: 'AI Development',
    shortDesc: 'Intelligent AI solutions including ML models, NLP, computer vision, and predictive analytics.',
    icon: Brain,
    category: 'AI & Automation',
    benefits: ['Predictive insights', 'Process automation', 'Data-driven decisions', 'Competitive advantage'],
    technologies: ['Python', 'TensorFlow', 'PyTorch', 'OpenAI', 'LangChain'],
    process: ['Data Assessment', 'Model Design', 'Training & Tuning', 'Integration', 'Monitoring & Improvement'],
  },
  {
    slug: 'ai-chatbots',
    title: 'AI Chatbots',
    shortDesc: 'Conversational AI chatbots that automate customer support and engagement 24/7.',
    icon: Bot,
    category: 'AI & Automation',
    benefits: ['24/7 availability', 'Reduced support costs', 'Multi-language', 'Learning capability'],
    technologies: ['OpenAI GPT', 'Dialogflow', 'Rasa', 'LangChain', 'Node.js'],
    process: ['Use Case Definition', 'Conversation Design', 'Bot Development', 'Training', 'Deployment & Analytics'],
  },
  {
    slug: 'automation',
    title: 'Automation',
    shortDesc: 'Streamline operations with intelligent workflow automation and RPA solutions.',
    icon: Zap,
    category: 'AI & Automation',
    benefits: ['Cost reduction', 'Error elimination', 'Faster processes', 'Scalable workflows'],
    technologies: ['n8n', 'Zapier', 'Python', 'Node.js', 'Selenium'],
    process: ['Process Mapping', 'Automation Design', 'Implementation', 'Testing', 'Monitoring & Optimization'],
  },
  {
    slug: 'crm-development',
    title: 'CRM Development',
    shortDesc: 'Custom CRM systems to manage leads, sales pipelines, and customer relationships.',
    icon: Database,
    category: 'Enterprise',
    benefits: ['360° customer view', 'Sales automation', 'Pipeline management', 'Custom reporting'],
    technologies: ['React', 'Node.js', 'PostgreSQL', 'Redis', 'Elasticsearch'],
    process: ['Business Analysis', 'CRM Architecture', 'Module Development', 'Data Migration', 'Training & Launch'],
  },
  {
    slug: 'erp-development',
    title: 'ERP Development',
    shortDesc: 'Comprehensive ERP systems that unify your business processes into one platform.',
    icon: Settings,
    category: 'Enterprise',
    benefits: ['Unified operations', 'Real-time reporting', 'Inventory management', 'Financial tracking'],
    technologies: ['React', 'Node.js', 'PostgreSQL', 'Docker', 'Kubernetes'],
    process: ['Business Process Analysis', 'System Design', 'Module Development', 'Integration', 'Go-Live Support'],
  },
  {
    slug: 'api-development',
    title: 'API Development',
    shortDesc: 'Robust, well-documented APIs that power your integrations and digital ecosystem.',
    icon: Cpu,
    category: 'Backend',
    benefits: ['RESTful & GraphQL', 'Versioned APIs', 'Rate limiting', 'Comprehensive docs'],
    technologies: ['Node.js', 'Express', 'GraphQL', 'Swagger', 'Postman'],
    process: ['API Design', 'Schema Definition', 'Development', 'Documentation', 'Versioning & Maintenance'],
  },
  {
    slug: 'backend-development',
    title: 'Backend Development',
    shortDesc: 'Scalable, secure backend systems that power your applications reliably.',
    icon: Server,
    category: 'Backend',
    benefits: ['High performance', 'Microservices ready', 'Database optimization', 'Secure by design'],
    technologies: ['Node.js', 'Python', 'Go', 'PostgreSQL', 'MongoDB'],
    process: ['Architecture Planning', 'Database Design', 'API Development', 'Security Hardening', 'Performance Tuning'],
  },
  {
    slug: 'frontend-development',
    title: 'Frontend Development',
    shortDesc: 'Pixel-perfect, responsive frontends with modern frameworks and exceptional UX.',
    icon: Layout,
    category: 'Development',
    benefits: ['Pixel perfect', 'Responsive design', 'Accessible', 'Performance optimized'],
    technologies: ['React', 'Next.js', 'Vue.js', 'TypeScript', 'CSS3'],
    process: ['Design System Setup', 'Component Development', 'State Management', 'Testing', 'Performance Optimization'],
  },
  {
    slug: 'cloud-solutions',
    title: 'Cloud Solutions',
    shortDesc: 'Cloud infrastructure, migration, and managed services for maximum scalability.',
    icon: Cloud,
    category: 'Infrastructure',
    benefits: ['Auto-scaling', 'Cost optimization', 'Global availability', 'Disaster recovery'],
    technologies: ['AWS', 'Azure', 'GCP', 'Docker', 'Kubernetes'],
    process: ['Cloud Assessment', 'Architecture Design', 'Migration', 'Optimization', 'Managed Support'],
  },
  {
    slug: 'devops',
    title: 'DevOps',
    shortDesc: 'CI/CD pipelines, infrastructure as code, and DevOps culture transformation.',
    icon: Settings,
    category: 'Infrastructure',
    benefits: ['Faster deployments', 'Infrastructure as code', 'Monitoring & alerts', 'Zero-downtime deploys'],
    technologies: ['Docker', 'Kubernetes', 'GitHub Actions', 'Terraform', 'Prometheus'],
    process: ['Current State Assessment', 'Pipeline Design', 'Implementation', 'Automation', 'Continuous Improvement'],
  },
  {
    slug: 'ui-ux-design',
    title: 'UI/UX Design',
    shortDesc: 'User-centered design that combines aesthetics with intuitive functionality.',
    icon: PenTool,
    category: 'Design',
    benefits: ['User research driven', 'Wireframes & prototypes', 'Design systems', 'Usability testing'],
    technologies: ['Figma', 'Adobe XD', 'Framer', 'Principle', 'Maze'],
    process: ['User Research', 'Information Architecture', 'Wireframing', 'Visual Design', 'Prototype & Test'],
  },
  {
    slug: 'ecommerce-development',
    title: 'Ecommerce Development',
    shortDesc: 'Feature-rich online stores with payment gateways, inventory, and analytics.',
    icon: ShoppingCart,
    category: 'Development',
    benefits: ['Multi-payment gateways', 'Inventory management', 'Analytics dashboard', 'SEO optimized'],
    technologies: ['Shopify', 'WooCommerce', 'Next.js', 'Stripe', 'Medusa'],
    process: ['Store Planning', 'Design & UX', 'Development', 'Payment Integration', 'Launch & Marketing'],
  },
  {
    slug: 'seo-optimization',
    title: 'SEO Optimization',
    shortDesc: 'Data-driven SEO strategies to boost your visibility and organic traffic.',
    icon: Search,
    category: 'Marketing',
    benefits: ['Higher rankings', 'Organic traffic growth', 'Technical SEO', 'Content strategy'],
    technologies: ['Google Analytics', 'Search Console', 'Ahrefs', 'SEMrush', 'Schema.org'],
    process: ['SEO Audit', 'Keyword Research', 'On-Page Optimization', 'Content Strategy', 'Reporting & Iteration'],
  },
  {
    slug: 'performance-optimization',
    title: 'Performance Optimization',
    shortDesc: 'Make your applications blazing fast with expert performance tuning.',
    icon: Gauge,
    category: 'Infrastructure',
    benefits: ['Faster load times', 'Better Core Web Vitals', 'Reduced bounce rate', 'Higher conversions'],
    technologies: ['Lighthouse', 'WebPageTest', 'CDN', 'Redis', 'Cloudflare'],
    process: ['Performance Audit', 'Bottleneck Analysis', 'Optimization', 'CDN & Caching', 'Monitoring'],
  },
  {
    slug: 'maintenance-support',
    title: 'Maintenance & Support',
    shortDesc: 'Ongoing maintenance, monitoring, and support to keep your systems running smoothly.',
    icon: Wrench,
    category: 'Services',
    benefits: ['24/7 monitoring', 'Regular updates', 'Bug fixes', 'Performance reports'],
    technologies: ['Sentry', 'Datadog', 'PagerDuty', 'GitHub', 'Jira'],
    process: ['System Assessment', 'SLA Agreement', 'Monitoring Setup', 'Regular Maintenance', 'Incident Response'],
  },
  {
    slug: 'security-consulting',
    title: 'Security Consulting',
    shortDesc: 'Protect your digital assets with comprehensive security audits and hardening.',
    icon: Shield,
    category: 'Services',
    benefits: ['Vulnerability assessment', 'Penetration testing', 'Compliance', 'Security training'],
    technologies: ['OWASP', 'Burp Suite', 'Snyk', 'SonarQube', 'Vault'],
    process: ['Security Audit', 'Risk Assessment', 'Remediation Plan', 'Implementation', 'Ongoing Monitoring'],
  },
];

export const SERVICE_CATEGORIES = [
  'All', 'Development', 'AI & Automation', 'Enterprise', 'Backend', 'Infrastructure', 'Design', 'Marketing', 'Services'
];
